### ISSUE TITLE
view/frontend/web/js/view/payment/method-renderer/billink.js needs another check for quote.billingAddress()

### ISSUE THREAD

**Issue by jrswgtr** [Billinkbv/Magento-2#18]
`quote.billingAddress()` can also be `null` instead of `undefined`. This happens in the native magento onepage checkout, when "My billing and shipping address are the same" is unchecked.

Please change line 80 from:

    if (quote.billingAddress() !== undefined) {  

To:

    if (quote.billingAddress() !== undefined && quote.billingAddress() !== null) {

Edit: 

There also seems to be a problem on line 220:

> billink.js:220 Uncaught TypeError: Cannot read properties of null (reading 'company')
>     at UiClass.isSelectedWorkflow (billink.js:220:52)
>     at visible (eval at createBindingsStringEvaluator (knockout.js:3221:28), <anonymous>:3:67)
>     at evaluateValueAccessor (knockout.js:3494:28)
>     at knockout.js:3671:44
>     at update (knockout.js:5519:59)
>     at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3745:45)
>     at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2331:115)
>     at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2288:41)
>     at Function.evaluateImmediate (knockout.js:2253:40)
>     at Function.evaluatePossiblyAsync (knockout.js:2218:44)

Changing the line to the following disables Billink when you manually uncheck the box.

    if (quote.billingAddress() !== null && !(typeof quote.billingAddress().company === undefined || quote.billingAddress().company === null)) {

So I temporarily fixed it by putting this above:

    if (quote.billingAddress() === null) {
        return this.selectedCustomerType() === 'B';
    }

**Comment by JSeverein** [comment]
We also have the same problem in the Mageplaza OneStepCheckout.
  
With this line giving an error as well:                  
`if (quote.billingAddress().street.length) {
`
