### ISSUE TITLE
\Billink\Billink\Observer\ShipmentObserver does not use StoreManagerInterface

### ISSUE THREAD

**Issue by pepijnblom** [Billinkbv/Magento-2#2]
While trying to use `bin/magento setup:di:compile` under Magento 2.4.1 with your 1.2.0 module I got the following error:

```
Compilation was started.
Area configuration aggregation... 5/9 [===============>------------]  55% 1 min 302.0 MiB
In ClassReader.php line 45:

  Impossible to process constructor argument Parameter #2 [ <required> Billink\Billink\Observer\StoreManagerInterface $storeManager ] of Billink\Billink\Observer\ShipmentObserver class


In ClassReader.php line 34:

  Class Billink\Billink\Observer\StoreManagerInterface does not exist


setup:di:compile
```

After looking in `\Billink\Billink\Observer\ShipmentObserver` it was clear that the `use Magento\Store\Model\StoreManagerInterface;` line was missing.

**Comment by bethlehemit** [comment]
Hi Pepijn, 
Version 1.3.0 (just published) resolves this mistake, and fixes the calendar on Magento 2.4
If you run into any other issues, please let me know
Ronald
