### ISSUE TITLE
@Billinkbv probably this is why you are still only providing 1.3.8:

### ISSUE THREAD

**Issue by mlaurense** [Billinkbv/Magento-2#24]
Please see my comment on your previously closed issue:

              @Billinkbv probably this is why you are still only providing 1.3.8:
![Scherm­afbeelding 2023-07-31 om 16 13 10](https://github.com/Billinkbv/Magento-2/assets/16759472/e4aab851-14f6-40cc-8d6b-7b195da0ddd6)

![Scherm­afbeelding 2023-07-31 om 16 13 34](https://github.com/Billinkbv/Magento-2/assets/16759472/8bce9e84-72e8-4fc6-8dde-6f2718cbdda0)

_Originally posted by @mlaurense in https://github.com/Billinkbv/Magento-2/issues/23#issuecomment-1658458225_

**Comment by Billinkbv** [comment]
Goodmorning @mlaurense,

This should be fixed now.
