### ISSUE TITLE
Compatibility issues with 2.4.6+ / Deprecated Zend Client

### ISSUE THREAD

**Issue by jeroenbalk-adwise** [Billinkbv/Magento-2#25]
Hello,

We are implementing Billink for a client. This results in an error in the Billink payment method box when submitting in checkout:

User Deprecated Functionality: Class is deprecated in /var/domains/xx/application/releases/455/vendor/magento/framework/HTTP/ZendClient.php on line 27

It seems usage of the ZendClient is deprecated as of 2.4.6, and Laminas Client should be used.

Regards,
Jeroen Balk
Adwise - Your Digital Brain

**Comment by Billinkbv** [comment]
Goodmorning Jeroen,

we just released version 2.0.0 which should fix these issues.
