### ISSUE TITLE
Suggestion: improve translation by using already translated words

### ISSUE THREAD

**Issue by mlaurense** [Billinkbv/Magento-2#28]
On several occasions the word 'telephone' is used:
https://github.com/Billinkbv/Magento-2/blob/master/view/frontend/web/template/payment/form.html#L65
https://github.com/Billinkbv/Magento-2/blob/master/view/frontend/web/template/payment/form.html#L186

However, this word is not in the standard Magento repository, hence it is not translated in the default available language packs (for example: https://github.com/magento-l10n/language-nl_NL)
The term 'Phone Number' is used in Magento and translated in most (if not all) language packs: https://github.com/magento-l10n/language-nl_NL/blob/master/nl_NL.csv#L2798

**Comment by Billinkbv** [comment]
Thanks for your comment. Sorry for the late reaction. We will try to fix this in the next version.
