### ISSUE TITLE
Translation errors/typo's

### ISSUE THREAD

**Issue by mlaurense** [Billinkbv/Magento-2#32]
There are typo's in the following files:
https://github.com/Billinkbv/Magento-2/blob/master/i18n/nl_NL.csv#L15
https://github.com/Billinkbv/Magento-2/blob/master/i18n/en_US.csv#L15

"Minimale leeftijd voor bestellingen via Billink is 16 jaarm" <-- Should be 'jaar' and not 'jaarm'.

**Comment by Billinkbv** [comment]
hi @mlaurense, a new change is ready to install: https://github.com/Billinkbv/Magento-2/releases/tag/2.0.4
