### ISSUE TITLE
Shipping tax amount calculated incorrectly

### ISSUE THREAD

**Issue by dhacquebord** [Billinkbv/Magento-2#40]
https://github.com/Billinkbv/Magento-2/blob/960963b2f0c399a051b5e69d18a03cb4a7f519cf/Gateway/Request/Midpage/SessionCreate/Transaction.php#L80

The line above resulted in a value of `17.36`. I think this should be:
```
'taxRate' => (string)(round($order->getShippingTaxAmount() * 100 / $order->getShippingAmount())),
```

**Comment by Billinkbv** [comment]
Thanks for the report. We've created a ticket for this issue at our support partner.
