### ISSUE TITLE
Error when company is null

### ISSUE THREAD

**Issue by dhacquebord** [Billinkbv/Magento-2#41]
https://github.com/Billinkbv/Magento-2/blob/960963b2f0c399a051b5e69d18a03cb4a7f519cf/Gateway/Request/Midpage/SessionCreate/Customer.php#L41

This line throws an error when the value of company is `null`. I think this should be:

```
$company = trim($address->getCompany() || "");
```
(or something similar of course 🙂)

**Comment by Billinkbv** [comment]
Thanks for the report. We've created a ticket for this issue at our support partner.
