### ISSUE TITLE
taxRate calculation for shipping fails due to rounding differences

### ISSUE THREAD

**Issue by thomaske** [Billinkbv/Magento-2#43]
In `\Billink\Billink\Gateway\Request\Midpage\SessionCreate\Transaction::prepareItems()` the `taxRate` for shipping is calculated based on the taxAmount on the order (`getShippingTaxAmount()`). In general, the shipping costs are low, and the calculated VAT is sensitive to rounding differences. As a result, it does not seem possible to calculate the vatRate based on the calculated VAT.

For example:
* Shippingcosts amount: 3.95, tax rate: 21%
* Calculated tax amount by Magento: €0.68
* Calculated tax rate by Billink: 17,21% (0.68 * 100 / 3.95)

In `\Billink\Billink\Gateway\Converter\Order\ItemsConverter::addShippingAmountItem()`, the vatRate is calculated correctly.

**Comment by Billinkbv** [comment]
Hi Thomas, 

Thanks for your message. We will forward this to our Supportpartner.

**Comment by Billinkbv** [comment]
Hi Thomas,

We've patched a fix on version 2.1.5. You can check it here. 
https://github.com/Billinkbv/Magento-2/releases/tag/2.1.5
