### ISSUE TITLE
Billink Fee. Offline credit memo/Invoice created without Tax included

### ISSUE THREAD

**Issue by yuriichayka** [Billinkbv/Magento-2#8]
Hello, 

Looks like we stumbled upon the following bug. Please check.

Preconditions:
- Magento 2.4.3 Community
- Billink module 1.3.4

Description:
- With enabled Billink Fee, Credit Memo is being created without Tax included. But when you disable the fee - it works fine. 
- Looks like this is because of the missing  `base_tax_invoiced` and `tax_invoiced` in the `sales_order` table.
- **Invoice doesn't contain Tax either**.
STR:
- enable Billink Fee in Magento Admin;
- Place order;
- Try to create offline Credit memo in Magento Admin.

ER: Tax is included in Credit Memo;
AR: Tax is missing for Billink orders with fee when creating Credit Memo. 
![issue_tax](https://user-images.githubusercontent.com/34608132/148389850-0f4720d4-a89c-4fef-8859-4429304da7f5.png)
![configuration_billink](https://user-images.githubusercontent.com/34608132/148389851-5c684df2-8138-4c1f-9b41-a2e53cfe11e3.png)

**Comment by Billinkbv** [comment]
If this is still a problem, please contact us on support@billink.nl
