### ISSUE TITLE
‘Enable Invoice Emails' configuration doesn't work

### ISSUE THREAD

**Issue by yuriichayka** [Billinkbv/Magento-2#9]
Preconditions:

Magento 2.4.3 Community
Billink module 1.3.4

The configuration doesn't work because the plugin declaration was removed from etc/di.xml file.
See https://github.com/Billinkbv/Magento-2/commit/138f957c4aa40ef218999fce63e86c7b549e9c86

**Comment by Billinkbv** [comment]
If this is still a problem, please contact us on support@billink.nl
